name: SGFP
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  http_server: ^0.9.8+1
  http: 0.12.2
  mongo_dart: ^0.3.6

dev_dependencies:
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.12.2
  pedantic: ^1.9.0
  test: ^1.6.3
